---
- name: Symlink .editorconfig
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../roles/editorconfig/files/editorconfig"
    dest: "{{ ansible_facts['user_dir'] }}/.editorconfig"
    state: link
