---
fonts_firacode_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_nerd_fonts_version }}/FiraCode.zip"
fonts_monaspace_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_nerd_fonts_version }}/Monaspace.zip"
