---
- name: Install starship (Mac)
  when: is_mac
  community.general.homebrew:
    name: starship
    state: present

- name: Install starship (Linux)
  when: not is_mac
  become: "{{ should_become }}"
  block:
    - name: Download starship installer
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'
    
    - name: Execute starship installer
      ansible.builtin.shell: |
        set -o pipefail
        /tmp/starship_install.sh -y
      args:
        creates: /usr/local/bin/starship
        executable: /bin/bash

- name: Create starship config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Symlink starship config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../roles/starship/files/starship.toml"
    dest: ~/.config/starship.toml
    state: link
