---
- name: Install starship (Mac)
  when: is_mac
  community.general.homebrew:
    name: starship
    state: present

- name: Install starship (Linux)
  when: not is_mac
  become: "{{ should_become }}"
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship

- name: Create starship config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Copy starship config
  ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
    mode: '0644'
